### ISSUE TITLE
IllegalAccessError for OnApplyInsetsListener

### ISSUE THREAD

**Issue by SteinerOk** [chrisbanes/insetter#14]
Insetter version: **0.1.0** with ktx
I start use insetter and catch this exception:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.desk.gesture_view, PID: 4053
    java.lang.IllegalAccessError: Interface dev.chrisbanes.insetter.OnApplyInsetsListener implemented by class ru.desk.gesture_view.ImageViewerActivity$onCreate$$inlined$doOnApplyWindowInsets$1 is inaccessible (declaration of 'ru.desk.gesture_view.ImageViewerActivity$onCreate$$inlined$doOnApplyWindowInsets$1' appears in /data/app/ru.desk.gesture_view-u1iHhsBDTS7EvCxxHDbseQ==/base.apk!classes2.dex)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1216)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

I think problem is that **OnApplyInsetsListener** is not public...

**Comment by SteinerOk** [comment]
Updated to 0.1.1 and received new problem:
```
Duplicate class dev.chrisbanes.insetter.ViewinsetterKt found in modules classes.jar (dev.chrisbanes.insetter:insetter-ktx:0.1.1) and classes.jar (dev.chrisbanes:insetter-ktx:0.1.1)
Duplicate class dev.chrisbanes.insetter.ViewinsetterKt$doOnApplyWindowInsets$1 found in modules classes.jar (dev.chrisbanes.insetter:insetter-ktx:0.1.1) and classes.jar (dev.chrisbanes:insetter-ktx:0.1.1)
```
Used dependencies:
```
    implementation "dev.chrisbanes:insetter:0.1.1"
    implementation "dev.chrisbanes:insetter-ktx:0.1.1"
```

**Comment by chrisbanes** [comment]
Have you tried clearing Gradle build caches? v0.1.1 is working for me:

**Comment by SteinerOk** [comment]
Yes, executed **clean** and **cleanBuildCache** tasks

I solved this problem with replacing dependencies from 
```
    implementation "dev.chrisbanes:insetter:0.1.1"
    implementation "dev.chrisbanes:insetter-ktx:0.1.1"
```
to 
```
    implementation "dev.chrisbanes.insetter:insetter:0.1.1"
    implementation "dev.chrisbanes.insetter:insetter-ktx:0.1.1"
```
and now works :)
