### ISSUE TITLE
InsetterConstraintLayout does not work with ConstraintLayout 2.1.0-alpha2

### ISSUE THREAD

**Issue by Stonos** [chrisbanes/insetter#79]
[ConstraintLayout 2.1.0-alpha2](https://androidstudio.googleblog.com/2020/12/constraintlayout-210-alpha-2.html) introduced the following change:

> `ConstraintLayout.LayoutParams` now inherits directly from `ViewGroup.LayoutParams`, not `ViewGroup.MarginLayoutParams`.

This causes the following exception to be thrown when trying to use `InsetterConstraintLayout` with something like `app:layout_marginSystemWindowInsets`:

```
java.lang.IllegalArgumentException: Margin inset handling requested but view LayoutParams do not extend MarginLayoutParams
    at dev.chrisbanes.insetter.Insetter.applyInsetsToView(Insetter.java:459)
    at dev.chrisbanes.insetter.widgets.constraintlayout.InsetterConstraintLayout.onApplyWindowInsets(InsetterConstraintLayout.java:94)
    at android.view.View.dispatchApplyWindowInsets(View.java:9801)
    at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7076)
    at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7080)
    at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7080)
    at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7080)
    at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7080)
    at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7080)
    at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:1664)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1766)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
    at android.view.Choreographer.doFrame(Choreographer.java:696)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6718)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by chrisbanes** [comment]
I've raised this [bug](https://issuetracker.google.com/176221189) since this is an API breaking change in a minor version bump.

**Comment by chrisbanes** [comment]
Closing this, as it's no longer an issue in ConstraintLayout 2.1.0-beta01
